image: openjdk:latest

build:
  before_script:
    - export CLASSPATH=.:/builds/1617_grupo7/chatrooms-jms/lib/imq.jar
    - export CLASSPATH=$CLASSPATH:/builds/1617_grupo7/chatrooms-jms/lib/jms.jar
    - export CLASSPATH=$CLASSPATH:/builds/1617_grupo7/chatrooms-jms/lib/twitter-text-1.14.1.jar
    - export CLASSPATH=$CLASSPATH:/builds/1617_grupo7/chatrooms-jms/lib/jbcrypt-0.2.jar
  script: "bash compile.sh"
