CREATE DATABASE `chatrooms`;

USE `chatrooms`;

CREATE TABLE IF NOT EXISTS USER (
	handle VARCHAR(10) PRIMARY KEY,
	password VARCHAR(100) NOT NULL,
	last_conexion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	current_topic VARCHAR(15),
	status BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS CHATROOM (
	name VARCHAR(15) PRIMARY KEY,
	handle_creator VARCHAR(10) NOT NULL REFERENCES USER(handle) ON UPDATE CASCADE,
	create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE USER
ADD FOREIGN KEY (current_topic) REFERENCES CHATROOM(name) ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS MESSAGE (
	id INT PRIMARY KEY AUTO_INCREMENT,
	text VARCHAR(100) NOT NULL,
	handle_user VARCHAR(10) NOT NULL REFERENCES USER(handle) ON UPDATE CASCADE,
	name_chatroom VARCHAR(15) NOT NULL REFERENCES CHATROOM(name) ON UPDATE CASCADE,
	ids_mentioned VARCHAR(250),
	send_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suscription (
	handle_user VARCHAR(10) NOT NULL REFERENCES USER(handle) ON UPDATE CASCADE,
  name_chatroom VARCHAR(15) NOT NULL REFERENCES CHATROOM(name) ON UPDATE CASCADE,
  PRIMARY KEY(handle_user,name_chatroom)
);
